# Generated by Django 2.0.1 on 2018-01-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotname', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=10)),
                ('time', models.DateTimeField(verbose_name='start_time')),
                ('tycar', models.BooleanField()),
                ('parkspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkalot.slot')),
            ],
        ),
    ]
