# Generated by Django 2.0.1 on 2018-01-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkalot', '0002_auto_20180127_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tycar',
            new_name='Four_Wheeler',
        ),
        migrations.AddField(
            model_name='user',
            name='Two_Wheeler',
            field=models.BooleanField(default=False),
        ),
    ]
