# Generated by Django 2.0.1 on 2018-01-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkalot', '0003_auto_20180127_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='time',
            new_name='star_time',
        ),
    ]
